site_name: Introducción a la Documática, 1. Teoría.
nav:
- Inicio: index.md
- Introducción: intro.md
- Capítulo 1: man1.md
- Capítulo 2: man2.md
- Capítulo 3: man3.md
- Capítulo 4: man4.md
- Capítulo 5: man5.md
- Capítulo 6: man6.md
- Capítulo 7: man7.md
- Capítulo 8: man8.md
- Capítulo 9: man9.md
- Capítulo 10: man10.md
- 11. Bibliografía: man11.md

theme: readthedocs
