site_name: Introducción a la Documática, 1. Teoría.
nav:
- Inicio: index.md
- Introducción: intro.md
- 1. HACIA UN CONCEPTO BÁSICO DE DOCUMENTACIÓN AUTOMÁTICA/DOCUMÁTICA.: man1.md
- 2. LOS SISTEMAS DE BASES DE DATOS Y LOS SGBD.: man2.md
- 3. LA RECUPERACIÓN DE INFORMACIÓN.: man3.md
- Capítulo 4: man4.md
- Capítulo 5: man5.md
- Capítulo 6: man6.md
- Capítulo 7: man7.md
- Capítulo 8: man8.md
- Capítulo 9: man9.md
- Capítulo 10: man10.md
- 11. Bibliografía: man11.md

theme: readthedocs
